[package]
name = "puddler"
version = "0.7.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = "4.5.21"
colored = "2.1.0"
config = "0.14.1"
crossterm = "0.28.1"
dirs = "5.0.1"
discord-presence = { version = "1.4.1", features = [ "activity_type" ] }
futures = "0.3.31"
isahc = { version = "1.7.2", features = ["json"] }
isolanguage-1 = { version = "0.2.3", git = "https://github.com/Vernoxvernax/isolanguage-1.git" }
libmpv-sirno = "2.0.2-fork.1"
regex = "1.11.1"
serde = "1.0.215"
serde_derive = "1.0.215"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
toml = "0.8.19"
urlencoding = "2.1.3"
uuid = { version = "1.11.0", features = ["v4"] }
