[package]
name = "puddler"
version = "0.7.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
clap = "4.5.31"
colored = "3.0.0"
config = "0.15.8"
crossterm = "0.28.1"
dirs = "6.0.0"
discord-presence = { version = "1.5.0", features = [ "activity_type" ] }
futures = "0.3.31"
isahc = { version = "1.7.2", features = ["json"] }
isolanguage-1 = { version = "0.2.3", git = "https://github.com/Vernoxvernax/isolanguage-1.git" }
libmpv-sirno = "2.0.2-fork.1"
regex = "1.11.1"
serde = "1.0.218"
serde_derive = "1.0.218"
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }
toml = "0.8.20"
urlencoding = "2.1.3"
uuid = { version = "1.15.1", features = ["v4"] }
