[package]
name = "puddler"
version = "0.7.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = "4.5.4"
colored = "2.1.0"
config = { version = "0.14.0" }
crossterm = "0.27.0"
dirs = "5.0.1"
discord-presence = "1.2.0"
futures = "0.3.30"
isahc = { version = "1.7.2", features = ["json"] }
isolanguage-1 = { version = "0.2.3", git = "https://github.com/Vernoxvernax/isolanguage-1.git" }
libmpv-sirno = "2.0.2-fork.1"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
regex = "1.10.4"
serde = "1.0.200"
serde_derive = "1.0.200"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
urlencoding = "2.1.3"
uuid = { version = "1.8.0", features = ["v4"] }
