[package]
name = "puddler"
version = "0.6.1"
edition = "2021"

[dependencies]
isahc = { version = "1.7.2", features=["json"] }
uuid = { version = "1.8.0", features = ["v4"] }
config = { version = "0.14.0", features = ["yaml"] }
tokio = { version = "1.36.0", features = ["full"] }
chrono = { version = "0.4.35", features = ["alloc", "clock"] }
libmpv-sirno = "2.0.2-fork.1"
crossterm = "0.27.0"
serde = "1.0.197"
serde_json = "1.0.115"
serde_derive = "1.0.197"
http = "1.1.0"
colored = "2.1.0"
urlencoding = "2.1.3"
discord-presence = "1.1.1"
toml = "0.8.12"
regex = "1.10.4"
rpassword = "7.3.1"
dialoguer = "0.11.0"
clap = "4.5.4"
dirs = "5.0.1"
