[package]
name = "puddler"
version = "0.5.11"
edition = "2021"

[dependencies]
isahc = { version = "1.7.2", features=["json"] }
app_dirs = { package = "app_dirs2", version = "2.5.4" }
mpv = { git = "https://github.com/Vernoxvernax/mpv-rs.git" }
uuid = { version = "1.3.0", features = ["v4"] }
getch = "0.3.1"
config = { version = "0.13.3", features = ["yaml"] }
serde = "1.0.152"
serde_json = "1.0.93"
serde_derive = "1.0.152"
http = "0.2.8"
colored = "2.0.0"
urlencoding = "2.1.2"
discord-rich-presence = "0.2.3"
toml = "0.7.2"
regex = "1.7.1"
rpassword = "7.2.0"
dialoguer = "0.10.3"
tokio = { version = "1.25.0", features = ["full"] }
