[package]
name = "puddler"
version = "0.5.5"
edition = "2021"

[dependencies]
getch = "0.3.1"
isahc = { version = "1.7.2", features = ["json"]}
app_dirs = { package = "app_dirs2", version = "2.3" }
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
serde_derive = "1.0.137"
http = "0.2.7"
colored = "2.0.0"
urlencoding = "2.1.0"
mpv = { version = "0.2.4", path = "../mpv-rs"}
discord-rich-presence = "0.2.0"
uuid = { version = "1.1.2", features = ["v4"] }
config = { version = "0.13.1", features = ["yaml"] }
toml = "0.5.9"
