[package]
name = "puddler"
version = "0.5.12"
edition = "2021"

[dependencies]
isahc = { version = "1.7.2", features=["json"] }
app_dirs = { version = "2.5.5", package = "app_dirs2" }
mpv = { git = "https://github.com/Vernoxvernax/mpv-rs.git" }
uuid = { version = "1.3.0", features = ["v4"] }
config = { version = "0.13.3", features = ["yaml"] }
tokio = { version = "1.26.0", features = ["full"] }
getch = "0.3.1"
serde = "1.0.157"
serde_json = "1.0.94"
serde_derive = "1.0.157"
http = "0.2.9"
colored = "2.0.0"
urlencoding = "2.1.2"
discord-rich-presence = "0.2.3"
toml = "0.7.3"
regex = "1.7.1"
rpassword = "7.2.0"
dialoguer = "0.10.3"
