[package]
name = "puddler"
version = "0.5.13"
edition = "2021"

[dependencies]
isahc = { version = "1.7.2", features=["json"] }
uuid = { version = "1.5.0", features = ["v4"] }
config = { version = "0.13.3", features = ["yaml"] }
tokio = { version = "1.33.0", features = ["full"] }
chrono = { version = "0.4.31", features = ["alloc", "clock"] }
libmpv-sirno = "2.0.2-fork.1"
getch = "0.3.1"
serde = "1.0.189"
serde_json = "1.0.107"
serde_derive = "1.0.189"
http = "0.2.9"
colored = "2.0.4"
urlencoding = "2.1.3"
discord-presence = "0.5.18"
toml = "0.8.4"
regex = "1.10.2"
rpassword = "7.2.0"
dialoguer = "0.11.0"
clap = "4.4.7"
dirs = "5.0.1"
