# GitHub Actions workflow to build artifacts and create releases on the "main" branch

name: Create release

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libmpv-dev gcc-mingw-w64 -y
        rustup target add x86_64-pc-windows-gnu
    
    - name: Build Linux and Windows binaries
      run: |
        cargo build --release
        cargo build --release --target=x86_64-pc-windows-gnu
    
    - name: Rename artifacts
      run: |
        mv ./target/release/puddler puddler
        mv ./target/x86_64-pc-windows-gnu/release/puddler.exe puddler.exe
    
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: RECENT_CHANGES.md

    - name: Upload Linux build artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: puddler
        asset_name: puddler
        asset_content_type: application/octet-stream
    
    - name: Upload Windows build artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: puddler.exe
        asset_name: puddler.exe
        asset_content_type: application/octet-stream
