# GitHub Actions workflow to build artifacts and create releases on the "main" branch

name: Rust build

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libmpv-dev gcc-mingw-w64 -y
        rustup target add x86_64-pc-windows-gnu
    
    - name: Build Linux and Windows binaries
      run: |
        cargo build --release
        cargo build --release --target=x86_64-pc-windows-gnu
    
    - name: Rename artifacts
      run: |
        mv ./target/release/puddler puddler
        mv ./target/x86_64-pc-windows-gnu/release/puddler.exe puddler.exe
    
    - name: Release
      uses: softprops/action-gh-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: false
        prerelease: false
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        body_path: RECENT_CHANGES.md
        files: puddler, puddler.exe
